# Generated by Django 3.2.3 on 2022-02-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_orderitem_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bot.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantitation',
            field=models.SmallIntegerField(default=0),
        ),
    ]
